#include <stdio.h>
#include <math.h>

// Modular exponentiation: (base^exp) % mod
long long power(long long base, long long exp, long long mod) {
    long long result = 1;
    base = base % mod;
    while (exp > 0) {
        if (exp % 2 == 1)
            result = (result * base) % mod;
        exp = exp / 2;
        base = (base * base) % mod;
    }
    return result;
}

int main() {
    long long P, G;     // Publicly known prime (P) and primitive root (G)
    long long a, b;     // Alice's and Bob's private keys
    long long A, B;     // Public keys generated by Alice and Bob
    long long keyA, keyB; // Shared secret keys computed by both

    printf("Enter a prime number (P): ");
    scanf("%lld", &P);

    printf("Enter a primitive root modulo P (G): ");
    scanf("%lld", &G);

    // Alice chooses a private key
    printf("Enter Alice's private key (a): ");
    scanf("%lld", &a);

    // Bob chooses a private key
    printf("Enter Bob's private key (b): ");
    scanf("%lld", &b);

    // Step 1: Compute public keys
    A = power(G, a, P); // Alice's public key
    B = power(G, b, P); // Bob's public key

    printf("\nPublic keys generated:\n");
    printf("Alice sends A = %lld to Bob\n", A);
    printf("Bob sends B = %lld to Alice\n", B);

    // Step 2: Each computes the shared secret key
    keyA = power(B, a, P); // Alice computes key
    keyB = power(A, b, P); // Bob computes key

    printf("\nShared secret keys computed:\n");
    printf("Alice's Secret Key: %lld\n", keyA);
    printf("Bob's Secret Key:   %lld\n", keyB);

    if (keyA == keyB)
        printf("\n Shared secret successfully established!\n");
    else
        printf("\n Error: Keys do not match!\n");

    return 0;
}